### ISSUE TITLE
cqlb 下点号键无法用于输入字词编码

### ISSUE THREAD

**Issue by xbot** [whjiang/cqeb_rime#12]
例如：

无法用 `kzy.` 输入“可以”

**Comment by jacobleft** [comment]
新建或修改`default.custom.yaml`文件，添加
```yaml
patch:
  key_binder:
    bindings:
      __patch:
        - key_bindings:/paging_with_minus_equal
```
